package com.bytebattle.performance.repository;

import com.bytebattle.performance.entity.PerformanceRecord;
import com.bytebattle.performance.enums.ActivityType;

import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface PerformanceRecordRepository
        extends JpaRepository<PerformanceRecord, UUID> {

    /*
     * ============================================================
     * USER-SCOPED LOOKUPS
     * ============================================================
     */

    /**
     * Performance history for one authenticated user.
     */
    List<PerformanceRecord>
    findByUserIdOrderByCreatedAtDesc(
            String userId,
            Pageable pageable
    );

    /**
     * Performance history for one user and one concept.
     */
    List<PerformanceRecord>
    findByUserIdAndConceptIdOrderByCreatedAtDesc(
            String userId,
            UUID conceptId,
            Pageable pageable
    );

<<<<<<< HEAD
    Optional<PerformanceRecord> findByIdAndUserId(UUID id, UUID userId);

    Optional<PerformanceRecord> findTopByUserIdAndConceptIdOrderByCreatedAtDesc(
            UUID userId,
            UUID conceptId);
=======
    /**
     * Performance history for one user and activity type.
     */
    List<PerformanceRecord>
    findByUserIdAndActivityTypeOrderByCreatedAtDesc(
            String userId,
            ActivityType activityType,
            Pageable pageable
    );

    /**
     * Latest performance record for a user and concept.
     */
    Optional<PerformanceRecord>
    findTopByUserIdAndConceptIdOrderByCreatedAtDesc(
            String userId,
            UUID conceptId
    );

    /**
     * Ownership-protected lookup.
     *
     * User A cannot retrieve User B's record
     * merely by knowing the UUID.
     */
    Optional<PerformanceRecord>
    findByIdAndUserId(
            UUID id,
            String userId
    );

    /*
     * ============================================================
     * IDEMPOTENCY
     * ============================================================
     */

    /**
     * Finds an existing performance record generated by
     * the same source activity.
     *
     * Used to prevent duplicate evidence creation when
     * the same battle/submission request is processed twice.
     */
    Optional<PerformanceRecord>
    findByUserIdAndActivityTypeAndSourceId(
            String userId,
            ActivityType activityType,
            UUID sourceId
    );

    /*
     * ============================================================
     * POSTGRESQL AGGREGATIONS
     * ============================================================
     *
     * Statistics are calculated in the database instead of
     * loading every PerformanceRecord into Java.
     */

    @Query("""
            SELECT
                COUNT(r) AS totalActivities,
                AVG(r.accuracy) AS averageAccuracy,
                AVG(r.score) AS averageScore,
                COALESCE(
                    SUM(
                        CASE
                            WHEN r.success = true THEN 1L
                            ELSE 0L
                        END
                    ),
                    0L
                ) AS successCount,
                COALESCE(
                    SUM(r.hintsUsed),
                    0L
                ) AS totalHintsUsed,
                COALESCE(
                    SUM(r.timeSpentSeconds),
                    0L
                ) AS totalTimeSpentSeconds
            FROM PerformanceRecord r
            WHERE r.userId = :userId
            """)
    OverallStats getOverallStats(
            @Param("userId") String userId
    );

    /**
     * Average accuracy grouped by concept for one user.
     */
    @Query("""
            SELECT
                r.conceptId AS conceptId,
                AVG(r.accuracy) AS averageAccuracy
            FROM PerformanceRecord r
            WHERE r.userId = :userId
            GROUP BY r.conceptId
            """)
    List<ConceptAccuracy> getAccuracyByConcept(
            @Param("userId") String userId
    );

    /*
     * ============================================================
     * PROJECTION INTERFACES
     * ============================================================
     */

    interface OverallStats {

        Long getTotalActivities();

        Double getAverageAccuracy();

        Double getAverageScore();

        Long getSuccessCount();

        Long getTotalHintsUsed();

        Long getTotalTimeSpentSeconds();
    }

    interface ConceptAccuracy {

        UUID getConceptId();

        Double getAverageAccuracy();
    }

	Optional<PerformanceRecord> findFirstByUserIdAndConceptIdOrderByCreatedAtDesc(String userId, UUID conceptId);
>>>>>>> a2ff2d8 (Update backend)
}