name: byte_battle

description: Byte Battle onboarding and login UI.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Auth API integration ---
  dio: ^5.9.0                     # HTTP client used by ApiClient/AuthInterceptor
  flutter_secure_storage: ^11.0.0 # encrypted token/user storage
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
