# ===== Database Connection (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/bytebattle_db
spring.datasource.username=postgres
spring.datasource.password=Mubbi12@
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Flyway =====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===== Email (Gmail SMTP) - for Forgot Password =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhopalpoetryadda@gmail.com
spring.mail.password=xjpmdjvuwjhfxjqr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Used inside the reset password email link (update later when frontend exists)
app.frontend-url=http://localhost:3000

# ===== Server Port =====
server.port=8080